- name: Perform initial one-time setup
  ansible.builtin.import_playbook: plays/init.yml

- name: Setup users and user environments
  ansible.builtin.import_playbook: plays/users.yml

- name: Setup web infrastructure
  ansible.builtin.import_playbook: plays/web.yml
