- name: Delete dotfiles for {{ item.username }}
  ansible.builtin.file:
    path: "{{ item.homedir }}/.dotfiles"
    state: absent

- name: Clone dotfiles for {{ item.username }}
  ansible.builtin.command: git clone --bare https://github.com/rtyh12/dotfiles {{ item.homedir }}/.dotfiles
  
- name: Checkout dotfiles for {{ item.username }}
  ansible.builtin.command:
    # chdir: /root
    cmd: git --git-dir={{ item.homedir }}/.dotfiles --work-tree={{ item.homedir }} checkout -f

- name: Change shell to fish for {{ item.username }}
  become: yes
  user:
    name: "{{ item.username }}" 
    shell: /bin/fish