- name: Setup web infrastructure
  hosts: all
  tasks:
    - name: Add user nginx (TODO is this necessary?)
      become: true
      ansible.builtin.user:
        name: nginx
        shell: /sbin/nologin
        create_home: no
  
    - name: Install nginx
      become: true
      ansible.builtin.package:
        name:
          - nginx
        state: latest
        update-cache: true

    - name: Pull web-config
      git:
        repo: https://github.com/rtyh12/web-config
        dest: /home/cass/apps/web-config

    - name: Install nginx config from web-config
      ansible.builtin.command:
        chdir: /home/cass/apps/web-config
        cmd: /home/apps/web-config/install.sh

    - name: Pull triocards
      git:
        repo: https://github.com/rtyh12/triocards
        dest: /home/cass/apps/triocards

    - name: Pull rust-social
      git:
        repo: https://github.com/rtyh12/rust-social
        dest: /home/cass/apps/rust-social
